
services:
  mentor_bot:
    build: .
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    ports:
      - "80:80"

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: mentors
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  redis:
    image: redis:6.2
    ports:
      - "6380:6379"

volumes:
  postgres_data: