"""Initial migration

Revision ID: 6404e96df6cc
Revises: 21c449579b42
Create Date: 2024-09-18 21:26:54.009782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6404e96df6cc'
down_revision: Union[str, None] = '21c449579b42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mentors', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.String(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mentors', 'price',
               existing_type=sa.String(length=100),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    # ### end Alembic commands ###
