"""Add users table

Revision ID: fc518eff17d9
Revises: 56d823628437
Create Date: 2024-09-23 18:47:52.401330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc518eff17d9'
down_revision: Union[str, None] = '56d823628437'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mentors', sa.Column('speciality', sa.String(length=255), nullable=True))
    op.drop_column('mentors', 'specialty')
    op.add_column('users', sa.Column('first_name', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('country', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('spesiality', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('preferred_languages', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('experience_years', sa.SmallInteger(), nullable=True))
    op.add_column('users', sa.Column('grade', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('learning_goals', sa.String(length=250), nullable=True))
    op.add_column('users', sa.Column('mentor_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('last_active', sa.TIMESTAMP(), nullable=True))
    op.add_column('users', sa.Column('payment_status', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('feedback', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'users', 'mentors', ['mentor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'feedback')
    op.drop_column('users', 'payment_status')
    op.drop_column('users', 'last_active')
    op.drop_column('users', 'mentor_id')
    op.drop_column('users', 'learning_goals')
    op.drop_column('users', 'grade')
    op.drop_column('users', 'experience_years')
    op.drop_column('users', 'preferred_languages')
    op.drop_column('users', 'spesiality')
    op.drop_column('users', 'country')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.add_column('mentors', sa.Column('specialty', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('mentors', 'speciality')
    # ### end Alembic commands ###
